categories = ["Cutting Tools",
    "Measuring Instruments",
    "Plates",
    "Sheets",
    "Pipes",
    "Packaging Material",
    "Office Equipment",
    "Tools",
    "Wires and Cables",
    "Hardware",
    "Fastne",
    "Flanges",
    "Gearbox",
    "Electrical Heaters",
    "Paint",
    "Circuit Breakers",
    "Electrical switches",
    "Valves",
    "Oils and Lubricants",
    "Filters",
    "Hose Pipe",
    "Insulation Material",
    "Motors",
    "Abrasives",
    "Rubber Parts",
    "Bearing",
    "Safety Equipments",
    "Hydrolic Cylinders",
    "Hydrolic Accessories",
    "Pneumatic Cylinders",
    "Pneumatic Accessories ",
    "Industrial Belts and V Belts",
    "Welding Consumables",
    "Wire Mesh & Gratings",
    "Pipe Fittings",
    "Ropes",
    "Lifting Equipments",
    "Electrical Fittings",
    "Trolley Wheels",
    "Lifting Hooks, chains and clamps",
    "Springs",
    "Adhesive Tapes",
    "Plumbing Material",
]